"""empty message

Revision ID: 0e52c7f4e86a
Revises: c1c7a59000d4
Create Date: 2020-03-23 21:19:10.792091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e52c7f4e86a'
down_revision = 'c1c7a59000d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blood_types', sa.Column('rh', sa.String(length=1), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blood_types', 'rh')
    # ### end Alembic commands ###
