"""empty message

Revision ID: 1217a8bd74c4
Revises: 4df1fe74e1ed
Create Date: 2020-02-21 22:22:48.434359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1217a8bd74c4'
down_revision = '4df1fe74e1ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blood_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blood_type', sa.String(length=7), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blood_type')
    )
    op.create_table('ethnicities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ethnicity', sa.String(length=14), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('religions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('religion', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person_blood_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('blood_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blood_type_id'], ['blood_types.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person_ethnicities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('ethnicitie_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ethnicitie_id'], ['ethnicities.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person_religion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('religion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['religion_id'], ['religions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person_religion')
    op.drop_table('person_ethnicities')
    op.drop_table('person_blood_types')
    op.drop_table('religions')
    op.drop_table('ethnicities')
    op.drop_table('blood_types')
    # ### end Alembic commands ###
