"""empty message

Revision ID: 21fe497aa4e8
Revises: 79491f3a057c
Create Date: 2020-03-12 22:26:48.451656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21fe497aa4e8'
down_revision = '79491f3a057c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('religions', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('religions', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('religions', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('religions', sa.Column('observations', sa.String(length=500), nullable=True))
    op.add_column('religions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('religions', 'updated_at')
    op.drop_column('religions', 'observations')
    op.drop_column('religions', 'deleted_at')
    op.drop_column('religions', 'deleted')
    op.drop_column('religions', 'created_at')
    # ### end Alembic commands ###
