"""empty message

Revision ID: 26c41fcfe472
Revises: 02a3736033fa
Create Date: 2020-02-20 00:36:15.802481

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '26c41fcfe472'
down_revision = '02a3736033fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('users', 'name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
