"""empty message

Revision ID: 79491f3a057c
Revises: 795020113f3b
Create Date: 2020-03-12 21:10:38.897248

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '79491f3a057c'
down_revision = '795020113f3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person_blood_types')
    op.drop_table('person_religion')
    op.drop_table('person_ethnicities')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person_ethnicities',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('person_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('ethnicitie_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ethnicitie_id'], ['ethnicities.id'], name='person_ethnicities_ibfk_1'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name='person_ethnicities_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('person_religion',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('person_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('religion_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name='person_religion_ibfk_1'),
    sa.ForeignKeyConstraint(['religion_id'], ['religions.id'], name='person_religion_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('person_blood_types',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('person_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('blood_type_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['blood_type_id'], ['blood_types.id'], name='person_blood_types_ibfk_1'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name='person_blood_types_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
