"""empty message

Revision ID: 795020113f3b
Revises: ac80ec17161b
Create Date: 2020-02-23 01:25:44.948399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '795020113f3b'
down_revision = 'ac80ec17161b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('observations', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'observations')
    # ### end Alembic commands ###
