"""empty message

Revision ID: ac80ec17161b
Revises: 1217a8bd74c4
Create Date: 2020-02-21 22:35:56.827827

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ac80ec17161b'
down_revision = '1217a8bd74c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('person_blood_types', 'blood_type_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('person_blood_types', 'person_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('person_ethnicities', 'ethnicitie_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('person_ethnicities', 'person_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('person_religion', 'person_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('person_religion', 'religion_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('person_religion', 'religion_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('person_religion', 'person_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('person_ethnicities', 'person_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('person_ethnicities', 'ethnicitie_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('person_blood_types', 'person_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('person_blood_types', 'blood_type_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###
