"""empty message

Revision ID: c1c7a59000d4
Revises: 21fe497aa4e8
Create Date: 2020-03-23 20:47:34.675652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1c7a59000d4'
down_revision = '21fe497aa4e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('religions', sa.Column('denomination', sa.String(length=70), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('religions', 'denomination')
    # ### end Alembic commands ###
