"""empty message

Revision ID: c5d9337674a1
Revises: 0e52c7f4e86a
Create Date: 2020-03-23 21:20:05.383255

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c5d9337674a1'
down_revision = '0e52c7f4e86a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blood_types', 'rh')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blood_types', sa.Column('rh', mysql.VARCHAR(length=1), nullable=False))
    # ### end Alembic commands ###
