"""empty message

Revision ID: da7a0895a74e
Revises: 1aef317f86d4
Create Date: 2020-02-19 00:46:19.990751

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'da7a0895a74e'
down_revision = '1aef317f86d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_column('users', 'created')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created', mysql.DATETIME(), nullable=False))
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
